SELECT TOP 100 matforn.* FROM wfm_dsv.dbo.WFM_MATERIAL_FORNECEDOR matforn 
INNER JOIN wfm_dsv.dbo.WFM_FORNECEDORES forn ON matforn.COD_FORNECEDOR = forn.COD_FORNECEDOR
WHERE matforn.COD_FORNECEDOR IN(31094, 31101,31122)
--WHERE COD_MATERIAL = '001307276'
ORDER BY COD_FORNECEDOR;

SELECT TOP 100 * FROM wfm_dsv.dbo.TRD_MATERIAL mat
INNER JOIN wfm_dsv.dbo.TRD_PDM pdm ON mat.COD_PDM = pdm.COD_PDM
WHERE mat.COD_MATERIAL IN('001307276','000000007')

SELECT TOP 100 * FROM wfm_dsv.dbo.WFM_MATERIAL_FORNECEDOR matforn 
INNER JOIN wfm_dsv.dbo.TRD_MATERIAL mat ON mat.COD_MATERIAL = matforn.COD_MATERIAL
INNER JOIN wfm_dsv.dbo.TRD_PDM pdm ON mat.COD_PDM = pdm.COD_PDM
WHERE matforn.COD_FORNECEDOR = 31094
ORDER BY COD_FORNECEDOR, NOM_BASICO_TRAD;

SELECT TOP 100 mat.*, matforn.* FROM wfm_dsv.dbo.WFM_MATERIAL_FORNECEDOR matforn 
INNER JOIN wfm_dsv.dbo.TRD_MATERIAL mat ON mat.COD_MATERIAL = matforn.COD_MATERIAL
WHERE matforn.COD_MATERIAL = '001307276' AND matforn.COD_FORNECEDOR NOT IN(31094)


