using Ninject.Modules;
using WebForLink.Application.Interfaces;
using WebForLink.Application.Interfaces.WebForLink;
using WebForLink.Application.Services;
using WebForLink.Application.Services.Process;
using WebForLink.Web.Infrastructure;

namespace WebForLink.CrossCutting.InversionControl.Modules
{
    public class ApplicationServiceNinjectModule : NinjectModule
    {
        public override void Load()
        {
            Bind<IEmailAppService>().To<EmailAppService>();
            Bind<IArquivoAppService>().To<ArquivoAppService>();
            Bind<IBancoAppService>().To<BancoAppService>();
            Bind<ICarrinhoAppService>().To<CarrinhoAppService>();
            Bind<IContatoAppService>().To<ContatoAppService>();
            Bind<IDocumentoAnexadoAppService>().To<DocumentoAnexadoAppService>();
            Bind<IDocumentosSolicitacaoAppService>().To<DocumentosSolicitacaoAppService>();
            Bind<IEnderecoAppService>().To<EnderecoAppService>();
            Bind<IFichaCadastralAppService>().To<FichaCadastralAppService>();
            Bind<IListasDocumentoAppService>().To<ListasDocumentoAppService>();
            Bind<IListasSolicitanteAppService>().To<ListasSolicitanteAppService>();
            Bind<IResponsavelAppService>().To<ResponsavelAppService>();
            Bind<ISolicitacaoAppService>().To<SolicitacaoAppService>();
            Bind<ISolicitadoAppService>().To<SolicitadoAppService>();
            Bind<ISolicitanteAppService>().To<SolicitanteAppService>();
            Bind<IAcessoLogWebForLinkAppService>().To<AcessoLogWebForLinkAppService>();
            Bind<IAplicacaoWebForLinkAppService>().To<AplicacaoWebForLinkAppService>();
            Bind<IAprovacaoWebForLinkAppService>().To<AprovacaoWebForLinkAppService>();
            Bind<IBancoWebForLinkAppService>().To<BancoWebForLinkAppService>();
            Bind<ICadastroUnicoWebForLinkAppService>().To<CadastroUnicoWebForLinkAppService>();
            Bind<ICategoriaFornecedorChWebForLinkAppService>().To<CategoriaFornecedorChWebForLinkAppService>();
            Bind<ICategoriaIrfCodWebForLinkAppService>().To<CategoriaIrfCodWebForLinkAppService>();
            Bind<IConfiguracaoEmailContratanteWebForLinkAppService>()
                .To<ConfiguracaoEmailContratanteWebForLinkAppService>();
            Bind<IConfiguracaoWebForLinkAppService>().To<ConfiguracaoWebForLinkAppService>();
            Bind<IContrantanteFornecedorBancoWebForLinkAppService>()
                .To<ContrantanteFornecedorBancoWebForLinkAppService>();
            Bind<IContratanteArquivoWebForLinkAppService>().To<ContratanteArquivoWebForLinkAppService>();
            Bind<IContratanteConfiguracaoWebForLinkAppService>().To<ContratanteConfiguracaoWebForLinkAppService>();
            Bind<IContratanteFornecedorWebForLinkAppService>().To<ContratanteFornecedorWebForLinkAppService>();
            Bind<IContratanteOrganizacaoComprasWebForLinkAppService>()
                .To<ContratanteOrganizacaoComprasWebForLinkAppService>();
            Bind<IContratanteWebForLinkAppService>().To<ContratanteWebForLinkAppService>();
            Bind<IDescricaoDocumentosChWebForLinkAppService>().To<DescricaoDocumentosChWebForLinkAppService>();
            Bind<IDescricaoDocumentosWebForLinkAppService>().To<DescricaoDocumentosWebForLinkAppService>();
            Bind<IDescricaoWebForLinkAppService>().To<DescricaoWebForLinkAppService>();
            Bind<IDestinatarioWebForLinkAppService>().To<DestinatarioWebForLinkAppService>();
            Bind<IDocumentosCompartilhadosWebForLinkAppService>().To<DocumentosCompartilhadosWebForLinkAppService>();
            Bind<IDocumentoWebForLinkAppService>().To<DocumentoWebForLinkAppService>();
            Bind<IEnderecoWebForLinkAppService>().To<EnderecoWebForLinkAppService>();
            Bind<IExtensaoArquivoWebForLinkAppService>().To<ExtensaoArquivoWebForLinkAppService>();
            Bind<IFluxoSequenciaWebForLinkAppService>().To<FluxoSequenciaWebForLinkAppService>();
            Bind<IFluxoWebForLinkAppService>().To<FluxoWebForLinkAppService>();
            Bind<IFornecedorArquivoWebForLinkAppService>().To<FornecedorArquivoWebForLinkAppService>();
            Bind<IFornecedorBancoWebForLinkAppService>().To<FornecedorBancoWebForLinkAppService>();
            Bind<IFornecedorBaseContatoWebForLinkAppService>().To<FornecedorBaseContatoWebForLinkAppService>();
            Bind<IFornecedorBaseImportacaoWebForLinkAppService>().To<FornecedorBaseImportacaoWebForLinkAppService>();
            Bind<IFornecedorBaseWebForLinkAppService>().To<FornecedorBaseWebForLinkAppService>();
            Bind<IFornecedorVersaoDocumentosWebForLinkAppService>().To<FornecedorVersaoDocumentosWebForLinkAppService>();
            Bind<IFuncaoWebForLinkAppService>().To<FuncaoWebForLinkAppService>();
            Bind<IGrupoWebForLinkAppService>().To<GrupoWebForLinkAppService>();
            Bind<IImportacaoWebForLinkAppService>().To<ImportacaoWebForLinkAppService>();
            Bind<IInformacaoComplementarWebForLinkAppService>().To<InformacaoComplementarWebForLinkAppService>();
            Bind<IMeusCompartilhamentosWebForLinkAppService>().To<MeusCompartilhamentosWebForLinkAppService>();
            Bind<IMeusDocumentosWebForLinkAppService>().To<MeusDocumentosWebForLinkAppService>();
            Bind<IOrganizacaoComprasWebForLinkAppService>().To<OrganizacaoComprasWebForLinkAppService>();
            Bind<IPapelWebForLinkAppService>().To<PapelWebForLinkAppService>();
            Bind<IPerfilWebForLinkAppService>().To<PerfilWebForLinkAppService>();
            Bind<IPreCadastroWebForLinkAppService>().To<PreCadastroWebForLinkAppService>();
            Bind<IProcessoLoginWebForLinkAppService>().To<ProcessoLoginWebForLinkAppService>();
            Bind<IQuestionarioAbaPerguntaPapelWebForLinkAppService>()
                .To<QuestionarioAbaPerguntaPapelWebForLinkAppService>();
            Bind<IQuestionarioAbaPerguntaRespostaWebForLinkAppService>()
                .To<QuestionarioAbaPerguntaRespostaWebForLinkAppService>();
            Bind<IQuestionarioAbaPerguntaWebForLinkAppService>().To<QuestionarioAbaPerguntaWebForLinkAppService>();
            Bind<IQuestionarioAbaWebForLinkAppService>().To<QuestionarioAbaWebForLinkAppService>();
            Bind<IQuestionarioWebForLinkAppService>().To<QuestionarioWebForLinkAppService>();
            Bind<IRoboLogWebForLinkAppService>().To<RoboLogWebForLinkAppService>();
            Bind<IRoboWebForLinkAppService>().To<RoboWebForLinkAppService>();
            Bind<IServicosMateriaisWebForLinkAppService>().To<ServicosMateriaisWebForLinkAppService>();
            Bind<ISolicitacaoModificacaoBancoWebForLinkAppService>().To<SolicitacaoBancoWebForLinkAppService>();
            Bind<ISolicitacaoBloqueioWebForLinkAppService>().To<SolicitacaoBloqueioWebForLinkAppService>();
            Bind<ISolicitacaoCadastroFornecedorWebForLinkAppService>()
                .To<SolicitacaoCadastroFornecedorWebForLinkAppService>();
            Bind<ISolicitacaoModificacaoContatoWebForLinkAppService>().To<SolicitacaoContatoWebForLinkAppService>();
            Bind<ISolicitacaoDocumentosFornecedorWebForLinkAppService>()
                .To<SolicitacaoDocumentosFornecedorWebForLinkAppService>();
            Bind<ISolicitacaoMensagemWebForLinkAppService>().To<SolicitacaoMensagemWebForLinkAppService>();
            Bind<ISolicitacaoTramiteWebForLinkAppService>().To<SolicitacaoTramiteWebForLinkAppService>();
            Bind<ISolicitacaoMaterialEServicoWebForLinkAppService>()
                .To<SolicitacaoMaterialEServicoWebForLinkAppService>();
            Bind<ITipoBloqueioRoboWebForLinkAppService>().To<TipoBloqueioRoboWebForLinkAppService>();
            Bind<ITipoCadastroWebForLinkAppService>().To<TipoCadastroWebForLinkAppService>();
            Bind<ITipoDocumentosChWebForLinkAppService>().To<TipoDocumentosChWebForLinkAppService>();
            Bind<ITipoDocumentosWebForLinkAppService>().To<TipoDocumentosWebForLinkAppService>();
            Bind<ITipoGrupoWebForLinkAppService>().To<TipoGrupoWebForLinkAppService>();
            Bind<IUsuarioSenhaHistoricoWebForLinkAppService>().To<UsuarioSenhaHistoricoWebForLinkAppService>();
            Bind<IUsuarioWebForLinkAppService>().To<UsuarioWebForLinkAppService>();
            Bind<IVisaoWebForLinkAppService>().To<VisaoWebForLinkAppService>();
            Bind<IFornecedorContatoWebForLinkAppService>().To<FornecedorContatoWebForLinkAppService>();
            Bind<IFornecedorDocumentoWebForLinkAppService>().To<FornecedorDocumentoWebForLinkAppService>();
            Bind<IFornecedorEnderecoWebForLinkAppService>().To<FornecedorEnderecoWebForLinkAppService>();
            Bind<IFornecedorListaDocumentosWebForLinkAppService>().To<FornecedorListaDocumentosWebForLinkAppService>();
            Bind<IFornecedorRoboWebForLinkAppService>().To<FornecedorRoboWebForLinkAppService>();
            Bind<IFornecedorWebForLinkAppService>().To<FornecedorWebForLinkAppService>();
            Bind<IFornecedorServicoMaterialWebForLinkAppService>().To<FornecedorServicoMaterialWebForLinkAppService>();
            Bind<IFornecedorStatusWebForLinkAppService>().To<FornecedorStatusWebForLinkAppService>();
            Bind<IAbaPerguntaWebForLinkAppService>().To<AbaPerguntaWebForLinkAppService>();
            Bind<IRoboSintegraWebForLinkAppService>().To<RoboSintegraWebForLinkAppService>();
            Bind<ISolicitacaoDadosFiscaisWebForLinkAppService>().To<SolicitacaoDadosFiscaisWebForLinkAppService>();
            Bind<ISolicitacaoDesbloqueioWebForLinkAppService>().To<SolicitacaoDesbloqueioWebForLinkAppService>();
            Bind<ISolicitacaoDocumentoWebForLinkAppService>().To<SolicitacaoDocumentoWebForLinkAppService>();
            Bind<ISolicitacaoProrrogacaoPrazoWebForLinkAppService>()
                .To<SolicitacaoProrrogacaoPrazoWebForLinkAppService>();
            Bind<ISolicitacaoWebForLinkAppService>().To<SolicitacaoWebForLinkAppService>();
            Bind<ISolicitacaoStatusWebForLinkAppService>().To<SolicitacaoStatusWebForLinkAppService>();

            Bind<IFornecedorCategoriaWebForLinkAppService>().To<FornecedorCategoriaWebForLinkAppService>();
            Bind<ISolicitacaoModificacaoEnderecoWebForLinkAppService>().To<SolicitacaoModificacaoEnderecoWebForLinkAppService>();
            Bind<ISolicitacaoModificacaoDadosGeraisSequenciaWebForLinkAppService>().To<SolicitacaoModificacaoDadosGeraisSequenciaWebForLinkAppService>();
            Bind<ITramiteWebForLinkAppService>().To<TramiteWebForLinkAppService>();
            Bind<IAdesaoWebForLinkAppService>().To<AdesaoWebForLinkAppService>();
        }
    }
}