//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForLink.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebForLink.Web.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia.
        /// </summary>
        public static string Agencia {
            get {
                return ResourceManager.GetString("Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgenciaDigitoVerificador.
        /// </summary>
        public static string AgenciaDigitoVerificador {
            get {
                return ResourceManager.GetString("AgenciaDigitoVerificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Bairro {
            get {
                return ResourceManager.GetString("Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string CEP {
            get {
                return ResourceManager.GetString("CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Complemento {
            get {
                return ResourceManager.GetString("Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string Conta {
            get {
                return ResourceManager.GetString("Conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContaDigitoVerificador.
        /// </summary>
        public static string ContaDigitoVerificador {
            get {
                return ResourceManager.GetString("ContaDigitoVerificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados_Enderecos.
        /// </summary>
        public static string Dados_Enderecos {
            get {
                return ResourceManager.GetString("Dados_Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentoError.
        /// </summary>
        public static string DocumentoError {
            get {
                return ResourceManager.GetString("DocumentoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereco.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InscricaoEstadual.
        /// </summary>
        public static string InscricaoEstadual {
            get {
                return ResourceManager.GetString("InscricaoEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InscricaoMunicipal.
        /// </summary>
        public static string InscricaoMunicipal {
            get {
                return ResourceManager.GetString("InscricaoMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomeFantasia.
        /// </summary>
        public static string NomeFantasia {
            get {
                return ResourceManager.GetString("NomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt-BR.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazaoSocial.
        /// </summary>
        public static string RazaoSocial {
            get {
                return ResourceManager.GetString("RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
    }
}
